#!/bin/bash
#
# file create by liunianliang for clone project
#
repo_path=`which repo`

project_xml=""
case $1 in
	al817)
		project_xml="MT6753_L_MR1_BD1SW3_DEV.xml"
	;;
	al910)
		project_xml="BD1SW3_HQ6735_65T_B1A_M_DEV.xml"
	;;
	al815)
		project_xml="HQ6753_65C_B1P_L1_BD1SW3_DEV.xml"
	;;
	al1520)
		project_xml="HQ6753_65C_B1P_L1_BD1SW3_DEV.xml"
	;;
	aw733)
		project_xml="BD1SW3_HQ6580_WE_1LA_L_DEV.xml"
	;;
	al1555)
		project_xml="BD1SW3_QCOM_MSM8937_M_DEV.xml"
	;;
	*)
		project_xml="$1"
	;;
esac
echo "project_xml = $project_xml"
uri=`cat $repo_path | grep "192.168.130.18[9|1]:29418" | sed -e 's/repo/manifest/g' | awk -F '=' '{print $2}' | sed -e s/"'"//g`

#echo $uri

repo init --no-repo-verify -u $uri -m $project_xml
